### ISSUE TITLE
Unable to generate private key: exec: "openssl": executable file not found in $PATH

### ISSUE THREAD

**Issue by anhgelus** [anhgelus/writefreely-docker#2]
This error causes the server to crash

## Logs
```
2023/10/30 14:39:12 Unable to generate private key: exec: "openssl": executable file not found in $PATH
ERROR: 2023/10/30 14:39:12 database.go:2570: Unable to INSERT new activitypub keypair: NOT NULL constraint failed: collectionkeys.public_key
2023/10/30 14:39:12 "POST /api/collections/anhgelus/posts/is411tpenu" 200 25.392102ms "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
2023/10/30 14:39:12 Followers for 1: &[]
2023/10/30 14:39:12 POST 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10bb007]


goroutine 221 [running]:
github.com/writeas/web-core/activitypub.DecodePrivateKey({0x0?, 0x0?, 0x153c9a8?})
   /go/pkg/mod/github.com/writeas/web-core@v1.5.0/activitypub/keys.go:73 +0xa7
github.com/writefreely/writefreely.makeActivityPost({0xc0004e7c60, 0x1a}, 0xc000379a40, {0x0, 0x0}, {0x137a760, 0xc000e80a00})
   /source/activitypub.go:529 +0x551
github.com/writefreely/writefreely.federatePost(0xc000094120, 0xc000b0b540, 0x1, 0x1)
   /source/activitypub.go:754 +0xd2b
created by github.com/writefreely/writefreely.existingPost
   /source/posts.go:766 +0x7df
```

**Comment by anhgelus** [comment]
Looks like to be fixed in `c329007`. If it isn't, it will be reopened.
